### PR TITLE
Add EG25GGBR07A07M2G_30.003.30.003 firmware

### PR DESCRIPTION
**Pull request by AndreySV**
Firmware archive was taken from
https://storage.googleapis.com/helium-assets.nebra.com/modem-firmware/eg25g_firmware/EG25GGBR07A07M2G_30.003.30.003.tgz

### CODE REVIEW

**Comment by AndreySV** [comment]
I've not flashed this firmware

**Comment by Biktorgj** [comment]
I flashed the firmware and it does boot, and doesn't seem to break anything apparently (specially doesn't seem to enable secure boot)...

**Comment by AndreySV** [comment]
According to information from [Quectel ](https://cdn.sos.sk/productdata/1f/c5/963c4864/eg21ggb-128-sgns.pdf) this version is recommended update for EG25GGBR07A07M2G_01.003.01.003 after AT&T 3G sunset.

**Comment by Biktorgj** [comment]
The .006 you linked to in the chat seems to have those updates too, but better if we have them all :)

Thank you!

**Pull request merged**
